### ISSUE TITLE
Snips isn't wake up

### ISSUE THREAD

**Issue by wibimaster** [Psychokiller1888/snips-custom-hotword#1]
Hi, 

I follow your doc' from start to end, and my Hotword doesn't wake up Snips anymore :(

The hotword detection works great (can see it if I check `service snipsCustomHotword status`)

But if I run `snips-watch -vvv`, the hotword is detected by your service but not received by Snips :/

Is there a thing I have to check anywhere ? Thanks !

**-- EDIT --**

Seems to be Snips related, because `snips watch` fails to pop anything with this simple script:

```python
import paho.mqtt.publish as publish
import json

if __name__ == "__main__":
    test = publish.single(
        'hermes/hotword/default/detected',
        payload=json.dumps({'siteId': 'default'}),
        hostname='localhost',
        port=1883
    )
    print(test)

```

**Comment by Psychokiller1888** [comment]
Is the snips-hotword service running?

**Comment by wibimaster** [comment]
I tried with and without snips-hotword

**--EDIT--**

I can connect to MQTT server and catch "intent" event ; I can publish to hermes/dialogueManager/endSession too. Why is it just fail with hotword ? :(
